import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "magazine_language";

// Regroupe tous les textes traduits utilises par l'interface.
const translations = {
  fr: {
    common: {
      save: "Enregistrer",
      saving: "Enregistrement...",
      cancel: "Annuler",
      back: "Retour",
      close: "Fermer",
      delete: "Supprimer",
      edit: "Modifier",
      add: "Ajouter",
      reply: "Repondre",
      loading: "Chargement...",
      bio: "Bio",
      user: "Utilisateur",
      admin: "Admin",
      active: "Actif",
      suspended: "Suspendu",
      allRoles: "Tous les roles",
      allStatus: "Tous les statuts"
    },
    navbar: {
      login: "Connexion",
      articles: "Articles",
      mySpace: "Mon espace",
      admin: "Admin",
      addPost: "Ajouter un post",
      logout: "Deconnexion",
      language: "Langue"
    },
    auth: {
      login: "Connexion",
      register: "Inscription",
      username: "Nom d'utilisateur",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      forgotPasswordTitle: "Mot de passe oublie ?",
      forgotPasswordHint: "Un lien de reinitialisation sera envoye a l'adresse e-mail saisie.",
      forgotPasswordEnterEmail: "Veuillez d'abord saisir votre adresse e-mail.",
      forgotPasswordSent: "Si cette adresse existe, un lien de reinitialisation vient d'etre envoye.",
      forgotPasswordFailed: "Impossible d'envoyer le lien de reinitialisation pour le moment.",
      resetPasswordTitle: "Reinitialiser le mot de passe",
      resetPasswordHint: "Choisissez un nouveau mot de passe pour votre compte.",
      resetPasswordAction: "Mettre a jour",
      resetPasswordSuccess: "Votre mot de passe a ete reinitialise.",
      resetPasswordFailed: "Impossible de reinitialiser le mot de passe.",
      backToLogin: "Retour a la connexion",
      welcomeBack: "Bon retour",
      alreadyHaveAccount: "Vous avez deja un compte ?",
      helloFriend: "Bonjour",
      createAccount: "Creez votre compte et explorez Magazine203",
      usernameRequired: "Le nom d'utilisateur est obligatoire",
      usernameMinLength: "Le nom d'utilisateur doit contenir au moins 3 caracteres",
      emailRequired: "L'email est obligatoire",
      emailInvalid: "Veuillez saisir une adresse e-mail valide",
      passwordRequired: "Le mot de passe est obligatoire",
      passwordMinLength: "Le mot de passe doit contenir au moins 6 caracteres",
      confirmPasswordRequired: "Veuillez confirmer le mot de passe",
      loggingIn: "Connexion...",
      registering: "Inscription...",
      serverUnavailable: "Le serveur de connexion ne repond pas. Verifiez que le backend est lance.",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      loginFailed: "Echec de la connexion",
      registerFailed: "Echec de l'inscription",
      storageFullLogin: "Connexion reussie mais le stockage du navigateur est plein. Veuillez vider les donnees du site une fois.",
      storageFullRegister: "Inscription reussie mais le stockage du navigateur est plein. Veuillez vider les donnees du site une fois."
    },
    articleCard: {
      author: "Auteur Magazine203",
      pdfArticle: "Article PDF",
      save: "Enregistrer",
      saved: "Enregistre",
      readMore: "Lire plus"
    },
    articles: {
      mediaUnavailable: "Media indisponible",
      openPdf: "Ouvrir le PDF",
      profileUnavailable: "Profil indisponible",
      profileUnavailableText: "Nous n'avons pas pu charger ce profil pour le moment.",
      loadingProfile: "Chargement du profil...",
      loadingProfileText: "Veuillez patienter pendant le chargement du profil.",
      following: "Abonne",
      follow: "Suivre",
      browseAuthorPosts: "Parcourez les publications de cet auteur.",
      username: "Nom d'utilisateur",
      role: "Role",
      joined: "Inscrit le",
      posts: "Posts",
      likes: "Likes",
      views: "Vues",
      followers: "Abonnes",
      followingLabel: "Abonnements",
      articleNotFound: "Article introuvable",
      articleNotFoundText: "Cet article n'existe pas ou n'est plus disponible.",
      backToArticles: "Retour aux articles",
      loadingArticle: "Chargement de l'article...",
      like: "Like",
      comment: "Commentaire",
      view: "Vue",
      hideLikes: "Masquer les likes",
      showLikes: "Afficher les likes",
      hideViewers: "Masquer les vues",
      showViewers: "Afficher les vues",
      deletePost: "Supprimer le post",
      peopleWhoLiked: "Personnes qui ont aime vos posts",
      peopleWhoViewed: "Personnes qui ont consulte vos posts",
      peopleWhoCommented: "Personnes qui ont commente vos posts",
      likesSummary: "Tous les comptes qui ont aime un ou plusieurs de vos posts.",
      viewsSummary: "Tous les comptes qui ont consulte un ou plusieurs de vos posts.",
      viewerFallback: "Visiteur",
      commentsSummary: "Tous les comptes qui ont commente ou repondu a un ou plusieurs de vos posts.",
      noLikesYet: "Aucun like pour le moment",
      noViewersYet: "Aucune vue pour le moment",
      noCommentsYet: "Aucun commentaire pour le moment",
      writeComment: "Ecrire un commentaire...",
      editComment: "Modifier votre commentaire...",
      editReply: "Modifier votre reponse...",
      replyToComment: "Repondre a ce commentaire...",
      tapToChangeName: "Touchez pour changer votre nom",
      yourName: "Votre nom",
      shortBio: "Ecrivez une courte bio...",
      myPosts: "Mes posts",
      myLikes: "Mes likes",
      mySaves: "Mes enregistrements",
      createArticle: "Creer un article",
      createArticleText: "Ajoutez votre contenu et publiez-le.",
      newPost: "Nouveau post",
      openEditorText: "Ouvrir l'editeur.",
      openEditor: "Ouvrir l'editeur",
      uploadPost: "Importer un post",
      uploadArticle: "Importer votre article",
      uploadArticleText: "Ajoutez votre contenu et publiez votre article.",
      title: "Titre",
      description: "Description",
      articleTitle: "Titre de l'article",
      uploadMedia: "Importer une image, une video ou un PDF",
      uploadingFile: "Import du fichier...",
      selectedFile: "Fichier selectionne :",
      preview: "Apercu",
      publish: "Publier",
      latestArticles: "Derniers articles",
      loadingArticles: "Chargement des articles...",
      articlesSummary: "Ouvrez, aimez, enregistrez et commentez des articles."
    },
    admin: {
      adminPanel: "Panneau admin",
      dashboardAdmin: "Tableau de bord admin",
      overviewText: "Vue d'ensemble des posts, des auteurs et des utilisateurs de la plateforme.",
      totalPosts: "Total posts",
      totalUsers: "Total utilisateurs",
      admins: "Admins",
      totalLikes: "Total likes",
      totalViews: "Total vues",
      totalActivity: "Activite",
      overview: "Vue d'ensemble",
      activityBreakdown: "Repartition",
      activityBreakdownTitle: "Repartition de l'activite",
      topPosts: "Posts les plus performants",
      loadingDashboard: "Chargement du tableau de bord...",
      noChartData: "Aucune donnee disponible pour le diagramme.",
      noPostsYet: "Aucun post disponible pour le moment.",
      byAuthor: "Par",
      authors: "Auteurs",
      topContributors: "Principaux contributeurs",
      loadingAuthors: "Chargement des auteurs...",
      noAuthorsFound: "Aucun auteur trouve.",
      noEmailAvailable: "Aucun email disponible",
      points: "pts",
      topPostsChartTitle: "Courbe des posts les plus performants",
      topContributorsChartTitle: "Histogramme des principaux contributeurs",
      maxEngagement: "Engagement max",
      topContributorScore: "Score contributeur max",
      users: "Utilisateurs",
      userManagement: "Gestion des utilisateurs",
      searchByNameOrEmail: "Rechercher par nom ou email...",
      members: "Membres",
      noUsersMatch: "Aucun utilisateur ne correspond aux filtres actuels.",
      loadingUsers: "Chargement des utilisateurs...",
      joined: "Inscrit",
      openProfile: "Ouvrir le profil",
      makeUser: "Passer en utilisateur",
      makeAdmin: "Passer en admin",
      restoreAccess: "Retablir l'acces",
      suspend: "Suspendre",
      feed: "Flux",
      recentPublications: "Publications recentes",
      loadingPublications: "Chargement des publications...",
      noRecentPosts: "Aucun post recent trouve.",
      title: "Titre",
      author: "Auteur",
      actions: "Actions",
      comments: "Commentaires",
      created: "Cree",
      confirmDeletePost: "Supprimer definitivement ce post ?",
      deletePostFailed: "Impossible de supprimer ce post pour le moment.",
      commentsTracked: "Commentaires suivis",
      localAdminNotice: "Les actions utilisateur sont enregistrees localement si le backend n'expose pas encore les endpoints de gestion admin.",
      recently: "Recent"
    },
    footer: {
      copyright: "© 2025 Magazine203"
    }
  },
  en: {
    common: {
      save: "Save",
      saving: "Saving...",
      cancel: "Cancel",
      back: "Back",
      close: "Close",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      reply: "Reply",
      loading: "Loading...",
      bio: "Bio",
      user: "User",
      admin: "Admin",
      active: "Active",
      suspended: "Suspended",
      allRoles: "All roles",
      allStatus: "All status"
    },
    navbar: {
      login: "Login",
      articles: "Articles",
      mySpace: "My Space",
      admin: "Admin",
      addPost: "Add Post",
      logout: "Logout",
      language: "Language"
    },
    auth: {
      login: "Login",
      register: "Register",
      username: "Username",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      showPassword: "Show password",
      hidePassword: "Hide password",
      forgotPasswordTitle: "Forgot password?",
      forgotPasswordHint: "A password reset link will be sent to the email address entered.",
      forgotPasswordEnterEmail: "Please enter your email address first.",
      forgotPasswordSent: "If this address exists, a reset link has just been sent.",
      forgotPasswordFailed: "Unable to send the reset link right now.",
      resetPasswordTitle: "Reset password",
      resetPasswordHint: "Choose a new password for your account.",
      resetPasswordAction: "Update password",
      resetPasswordSuccess: "Your password has been reset.",
      resetPasswordFailed: "Unable to reset the password.",
      backToLogin: "Back to login",
      welcomeBack: "Welcome Back",
      alreadyHaveAccount: "Already have an account?",
      helloFriend: "Hello Friend",
      createAccount: "Create your account and explore Magazine203",
      usernameRequired: "Username is required",
      usernameMinLength: "Username must contain at least 3 characters",
      emailRequired: "Email is required",
      emailInvalid: "Please enter a valid email address",
      passwordRequired: "Password is required",
      passwordMinLength: "Password must contain at least 6 characters",
      confirmPasswordRequired: "Please confirm your password",
      loggingIn: "Signing in...",
      registering: "Signing up...",
      serverUnavailable: "The auth server is not responding. Make sure the backend is running.",
      passwordMismatch: "Passwords do not match",
      loginFailed: "Login failed",
      registerFailed: "Register failed",
      storageFullLogin: "Login succeeded but browser storage is full. Please clear site data once.",
      storageFullRegister: "Register succeeded but browser storage is full. Please clear site data once."
    },
    articleCard: {
      author: "Magazine203 author",
      pdfArticle: "PDF Article",
      save: "Save",
      saved: "Saved",
      readMore: "Read More"
    },
    articles: {
      mediaUnavailable: "Media unavailable",
      openPdf: "Open PDF",
      profileUnavailable: "Profile unavailable",
      profileUnavailableText: "We could not load this profile right now.",
      loadingProfile: "Loading profile...",
      loadingProfileText: "Please wait while we load this profile.",
      following: "Following",
      follow: "Follow",
      browseAuthorPosts: "Browse this author's published posts.",
      username: "Username",
      role: "Role",
      joined: "Joined",
      posts: "Posts",
      likes: "Likes",
      views: "Views",
      followers: "Followers",
      followingLabel: "Following",
      articleNotFound: "Article not found",
      articleNotFoundText: "This article does not exist or is no longer available.",
      backToArticles: "Back to articles",
      loadingArticle: "Loading article...",
      like: "Like",
      comment: "Comment",
      view: "View",
      hideLikes: "Hide likes",
      showLikes: "Show likes",
      hideViewers: "Hide viewers",
      showViewers: "Show viewers",
      deletePost: "Delete post",
      peopleWhoLiked: "People who liked your posts",
      peopleWhoViewed: "People who viewed your posts",
      peopleWhoCommented: "People who commented on your posts",
      likesSummary: "All accounts that liked one or more of your posts.",
      viewsSummary: "All accounts that viewed one or more of your posts.",
      viewerFallback: "Viewer",
      commentsSummary: "All accounts that commented or replied on one or more of your posts.",
      noLikesYet: "No likes yet",
      noViewersYet: "No viewers yet",
      noCommentsYet: "No comments yet",
      writeComment: "Write a comment...",
      editComment: "Edit your comment...",
      editReply: "Edit your reply...",
      replyToComment: "Reply to this comment...",
      tapToChangeName: "Tap to change your name",
      yourName: "Your name",
      shortBio: "Write a short bio about yourself...",
      myPosts: "My Posts",
      myLikes: "My Likes",
      mySaves: "My Saves",
      createArticle: "Create Article",
      createArticleText: "Add your content and publish it.",
      newPost: "New post",
      openEditorText: "Open the editor.",
      openEditor: "Open Editor",
      uploadPost: "Upload Post",
      uploadArticle: "Upload Your Article",
      uploadArticleText: "Add your content and publish your article.",
      title: "Title",
      description: "Description",
      articleTitle: "Article title",
      uploadMedia: "Upload an image, video, or PDF",
      uploadingFile: "Uploading file...",
      selectedFile: "Selected file:",
      preview: "Preview",
      publish: "Publish",
      latestArticles: "Latest Articles",
      loadingArticles: "Loading articles...",
      articlesSummary: "Open, like, save, and comment on articles."
    },
    admin: {
      adminPanel: "Admin panel",
      dashboardAdmin: "Admin dashboard",
      overviewText: "Overview of posts, authors, and platform users.",
      totalPosts: "Total posts",
      totalUsers: "Total users",
      admins: "Admins",
      totalLikes: "Total likes",
      totalViews: "Total views",
      totalActivity: "Activity",
      overview: "Overview",
      activityBreakdown: "Breakdown",
      activityBreakdownTitle: "Activity breakdown",
      topPosts: "Top performing posts",
      loadingDashboard: "Loading dashboard...",
      noChartData: "No data available for the chart.",
      noPostsYet: "No posts available yet.",
      byAuthor: "By",
      authors: "Authors",
      topContributors: "Top contributors",
      loadingAuthors: "Loading authors...",
      noAuthorsFound: "No authors found.",
      noEmailAvailable: "No email available",
      points: "pts",
      topPostsChartTitle: "Top performing posts line chart",
      topContributorsChartTitle: "Top contributors bar chart",
      maxEngagement: "Max engagement",
      topContributorScore: "Top contributor score",
      users: "Users",
      userManagement: "User management",
      searchByNameOrEmail: "Search by name or email...",
      members: "Members",
      noUsersMatch: "No users match the current filters.",
      loadingUsers: "Loading users...",
      joined: "Joined",
      openProfile: "Open profile",
      makeUser: "Make user",
      makeAdmin: "Make admin",
      restoreAccess: "Restore access",
      suspend: "Suspend",
      feed: "Feed",
      recentPublications: "Recent publications",
      loadingPublications: "Loading publications...",
      noRecentPosts: "No recent posts found.",
      title: "Title",
      author: "Author",
      actions: "Actions",
      comments: "Comments",
      created: "Created",
      confirmDeletePost: "Permanently delete this post?",
      deletePostFailed: "Unable to delete this post right now.",
      commentsTracked: "Comments tracked",
      localAdminNotice: "User actions are saved locally if the backend does not yet expose admin user-management endpoints.",
      recently: "Recently"
    },
    footer: {
      copyright: "© 2025 Magazine203"
    }
  },
  ar: {
    common: {
      save: "حفظ",
      saving: "جارٍ الحفظ...",
      cancel: "إلغاء",
      back: "رجوع",
      close: "إغلاق",
      delete: "حذف",
      edit: "تعديل",
      add: "إضافة",
      reply: "رد",
      loading: "جاري التحميل...",
      bio: "نبذة",
      user: "مستخدم",
      admin: "مشرف",
      active: "نشط",
      suspended: "موقوف",
      allRoles: "كل الأدوار",
      allStatus: "كل الحالات"
    },
    navbar: {
      login: "تسجيل الدخول",
      articles: "المقالات",
      mySpace: "مساحتي",
      admin: "الإدارة",
      addPost: "إضافة منشور",
      logout: "تسجيل الخروج",
      language: "اللغة"
    },
    auth: {
      login: "تسجيل الدخول",
      register: "إنشاء حساب",
      username: "اسم المستخدم",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      welcomeBack: "مرحبا بعودتك",
      alreadyHaveAccount: "هل لديك حساب بالفعل؟",
      helloFriend: "مرحبا",
      createAccount: "أنشئ حسابك واستكشف Magazine203",
      passwordMismatch: "كلمتا المرور غير متطابقتين",
      loginFailed: "فشل تسجيل الدخول",
      registerFailed: "فشل إنشاء الحساب",
      storageFullLogin: "تم تسجيل الدخول لكن مساحة تخزين المتصفح ممتلئة. يرجى مسح بيانات الموقع مرة واحدة.",
      storageFullRegister: "تم إنشاء الحساب لكن مساحة تخزين المتصفح ممتلئة. يرجى مسح بيانات الموقع مرة واحدة."
    },
    articleCard: {
      author: "كاتب Magazine203",
      pdfArticle: "مقال PDF",
      save: "حفظ",
      saved: "تم الحفظ",
      readMore: "اقرأ المزيد"
    },
    articles: {
      mediaUnavailable: "الوسائط غير متاحة",
      openPdf: "فتح ملف PDF",
      profileUnavailable: "الملف الشخصي غير متاح",
      profileUnavailableText: "تعذر تحميل هذا الملف الشخصي حاليا.",
      loadingProfile: "جاري تحميل الملف الشخصي...",
      loadingProfileText: "يرجى الانتظار أثناء تحميل الملف الشخصي.",
      following: "متابع",
      follow: "متابعة",
      browseAuthorPosts: "تصفح منشورات هذا الكاتب.",
      username: "اسم المستخدم",
      role: "الدور",
      joined: "تاريخ الانضمام",
      posts: "المنشورات",
      likes: "الإعجابات",
      views: "المشاهدات",
      followers: "المتابعون",
      followingLabel: "يتابع",
      articleNotFound: "المقال غير موجود",
      articleNotFoundText: "هذا المقال غير موجود أو لم يعد متاحا.",
      backToArticles: "العودة إلى المقالات",
      loadingArticle: "جاري تحميل المقال...",
      like: "إعجاب",
      comment: "تعليق",
      view: "مشاهدة",
      hideLikes: "إخفاء الإعجابات",
      showLikes: "عرض الإعجابات",
      hideViewers: "إخفاء المشاهدات",
      showViewers: "عرض المشاهدات",
      deletePost: "حذف المنشور",
      peopleWhoLiked: "الأشخاص الذين أعجبوا بمنشوراتك",
      peopleWhoViewed: "الأشخاص الذين شاهدوا منشوراتك",
      peopleWhoCommented: "الأشخاص الذين علقوا على منشوراتك",
      likesSummary: "كل الحسابات التي أعجبت بمنشور واحد أو أكثر من منشوراتك.",
      viewsSummary: "كل الحسابات التي شاهدت منشورا واحدا أو أكثر من منشوراتك.",
      viewerFallback: "Viewer",
      commentsSummary: "كل الحسابات التي علقت أو ردت على واحد أو أكثر من منشوراتك.",
      noLikesYet: "لا توجد إعجابات بعد",
      noViewersYet: "لا توجد مشاهدات بعد",
      noCommentsYet: "لا توجد تعليقات بعد",
      writeComment: "اكتب تعليقا...",
      editComment: "عدّل تعليقك...",
      editReply: "عدّل ردك...",
      replyToComment: "الرد على هذا التعليق...",
      tapToChangeName: "اضغط لتغيير اسمك",
      yourName: "اسمك",
      shortBio: "اكتب نبذة قصيرة عنك...",
      myPosts: "منشوراتي",
      myLikes: "إعجاباتي",
      mySaves: "محفوظاتي",
      createArticle: "إنشاء مقال",
      createArticleText: "أضف محتواك ثم انشره.",
      newPost: "منشور جديد",
      openEditorText: "افتح المحرر.",
      openEditor: "فتح المحرر",
      uploadPost: "رفع منشور",
      uploadArticle: "رفع مقالك",
      uploadArticleText: "أضف محتواك ثم انشر مقالك.",
      title: "العنوان",
      description: "الوصف",
      articleTitle: "عنوان المقال",
      uploadMedia: "ارفع صورة أو فيديو أو PDF",
      uploadingFile: "جاري رفع الملف...",
      selectedFile: "الملف المحدد:",
      preview: "معاينة",
      publish: "نشر",
      latestArticles: "أحدث المقالات",
      loadingArticles: "جاري تحميل المقالات...",
      articlesSummary: "افتح المقالات وأعجب بها واحفظها وعلّق عليها."
    },
    admin: {
      adminPanel: "لوحة الإدارة",
      dashboardAdmin: "لوحة تحكم المشرف",
      overviewText: "نظرة عامة على المنشورات والكتاب ومستخدمي المنصة.",
      totalPosts: "إجمالي المنشورات",
      totalUsers: "إجمالي المستخدمين",
      admins: "المشرفون",
      totalLikes: "إجمالي الإعجابات",
      totalViews: "إجمالي المشاهدات",
      totalActivity: "النشاط",
      overview: "نظرة عامة",
      activityBreakdown: "التوزيع",
      activityBreakdownTitle: "توزيع النشاط",
      topPosts: "أفضل المنشورات أداء",
      loadingDashboard: "جاري تحميل لوحة التحكم...",
      noChartData: "لا توجد بيانات لعرض المخطط.",
      noPostsYet: "لا توجد منشورات بعد.",
      byAuthor: "بواسطة",
      authors: "الكتاب",
      topContributors: "أكثر المساهمين",
      loadingAuthors: "جاري تحميل الكتاب...",
      noAuthorsFound: "لم يتم العثور على كتاب.",
      noEmailAvailable: "لا يوجد بريد إلكتروني",
      points: "نقطة",
      topPostsChartTitle: "مخطط خطي لأفضل المنشورات",
      topContributorsChartTitle: "مخطط أعمدة لأكثر المساهمين",
      maxEngagement: "أعلى تفاعل",
      topContributorScore: "أعلى نتيجة للمساهم",
      users: "المستخدمون",
      userManagement: "إدارة المستخدمين",
      searchByNameOrEmail: "ابحث بالاسم أو البريد الإلكتروني...",
      members: "الأعضاء",
      noUsersMatch: "لا يوجد مستخدمون يطابقون الفلاتر الحالية.",
      loadingUsers: "جاري تحميل المستخدمين...",
      joined: "انضم",
      openProfile: "فتح الملف الشخصي",
      makeUser: "تحويل إلى مستخدم",
      makeAdmin: "تحويل إلى مشرف",
      restoreAccess: "استعادة الوصول",
      suspend: "إيقاف",
      feed: "التغذية",
      recentPublications: "أحدث المنشورات",
      loadingPublications: "جاري تحميل المنشورات...",
      noRecentPosts: "لم يتم العثور على منشورات حديثة.",
      title: "العنوان",
      author: "الكاتب",
      comments: "التعليقات",
      created: "تاريخ الإنشاء",
      commentsTracked: "التعليقات المتتبعة",
      localAdminNotice: "يتم حفظ إجراءات المستخدم محليا إذا لم يوفّر الخلفية بعد واجهات إدارة المستخدمين للمشرف.",
      recently: "حديثا"
    },
    footer: {
      copyright: "© 2025 Magazine203"
    }
  }
};

// Decrit les langues disponibles et leur direction d'ecriture.
const languageMeta = {
  fr: { label: "FR", lang: "fr", locale: "fr-FR", dir: "ltr" },
  en: { label: "EN", lang: "en", locale: "en-US", dir: "ltr" },
  ar: { label: "AR", lang: "ar", locale: "ar-MA", dir: "rtl" }
};

// Partage la langue active et la fonction de traduction dans toute l'application.
const LanguageContext = createContext(null);

// Recupere la langue sauvegardee ou utilise le francais par defaut.
const getInitialLanguage = () => {
  const savedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return languageMeta[savedLanguage] ? savedLanguage : "fr";
};

// Complete les traductions arabes manquantes sans casser l'affichage.
const arabicFallbacks = {
  "auth.forgotPasswordTitle": "هل نسيت كلمة المرور؟",
  "auth.forgotPasswordHint": "سيتم إرسال رابط إعادة التعيين إلى عنوان البريد الإلكتروني المُدخل.",
  "auth.forgotPasswordEnterEmail": "يرجى إدخال عنوان البريد الإلكتروني أولاً.",
  "auth.forgotPasswordSent": "إذا كان هذا العنوان موجودًا، فقد تم إرسال رابط إعادة التعيين الآن.",
  "auth.forgotPasswordFailed": "تعذر إرسال رابط إعادة التعيين في الوقت الحالي.",
  "auth.showPassword": "إظهار كلمة المرور",
  "auth.hidePassword": "إخفاء كلمة المرور",
  "auth.resetPasswordTitle": "إعادة تعيين كلمة المرور",
  "auth.resetPasswordHint": "اختر كلمة مرور جديدة لحسابك.",
  "auth.resetPasswordAction": "تحديث كلمة المرور",
  "auth.resetPasswordSuccess": "تمت إعادة تعيين كلمة المرور.",
  "auth.resetPasswordFailed": "تعذرت إعادة تعيين كلمة المرور.",
  "auth.backToLogin": "العودة إلى تسجيل الدخول"
};

// Cherche une traduction par cle et retombe sur le francais si besoin.
const resolveTranslation = (language, key) => {
  const keys = key.split(".");
  let current = translations[language];

  for (const part of keys) {
    current = current?.[part];
  }

  if (typeof current === "string") {
    return current;
  }

  if (language === "ar" && arabicFallbacks[key]) {
    return arabicFallbacks[key];
  }

  let fallback = translations.fr;

  for (const part of keys) {
    fallback = fallback?.[part];
  }

  return typeof fallback === "string" ? fallback : key;
};

// Fournit la langue active, la direction RTL/LTR et la fonction t().
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);
  const meta = languageMeta[language] || languageMeta.fr;

  // Synchronise la langue choisie avec le DOM et le stockage local.
  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = meta.lang;
    document.documentElement.dir = meta.dir;
    document.body.dataset.language = language;
  }, [language, meta.dir, meta.lang]);

  // Memoise les informations de langue consommees par les composants.
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      locale: meta.locale,
      dir: meta.dir,
      isRTL: meta.dir === "rtl",
      options: Object.entries(languageMeta).map(([value, option]) => ({
        value,
        label: option.label
      })),
      t: (key) => resolveTranslation(language, key)
    }),
    [language, meta.dir, meta.locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// Hook pratique pour acceder au contexte de langue.
export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}

